name: Rayner Performance Testing

on:
  workflow_dispatch:
    inputs:
      testSuite:
        type: string
        description: 'TestSuite'
        required: true
        default: 'pokemonapi.PokemonApiTest'
jobs:
  execpokemonapi:
    runs-on: ubuntu-latest
    name: Executing Performance Pokemon API
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute test
        uses: gradle gatlingRun --simulation=pokemonapi.PokeminApiTest